baseURL = 'https://mathetake.github.io/'
languageCode = 'en-us'
theme = 'typo'
title = 'BitByteWise'

[params]
ogimage = "/favicon.ico"

# Appearance settings
theme = 'light'

# Collection to display on home
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = 'Jan 2 2006'

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/mathetake"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/mathetake/"

# Social icons
[[params.social]]
name = "twitter"
url = "https://x.com/mathetake"


[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'colorful'
